version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app_network
        depends_on:
            - db
        environment:
            DB_HOST: db
    db:
        image: postgres:16-alpine
        container_name: db
        restart: always
        environment:
            POSTGRES_DB: devhunts
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - app_network

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app_network

networks:
    app_network:

volumes:
    db_data:
