services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app_network
        depends_on:
            - db
        environment:
            DB_HOST: db
    db:
        image: postgres:16-alpine
        container_name: db
        restart: always
        environment:
            POSTGRES_DB: devhunts
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - app_network
        volumes:
            -   ./db_data:/var/lib/postgresql/data

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "127.0.0.1:8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app_network

networks:
    app_network:

volumes:
    db_data:
