version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-inertia-app
        container_name: laravel-inertia-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravelnet
        environment:
            - "DB_HOST=db"
            - "DB_PORT=5432"
            - "DB_DATABASE=devhunts"
            - "DB_USERNAME=root"
            - "DB_PASSWORD=root"

    db:
        image: postgres:16-alpine
        container_name: laravel-inertia-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: devhunts
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            - laravelnet
        volumes:
            - dbdata:/var/lib/postgres

    nginx:
        image: nginx:alpine
        container_name: laravel-inertia-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - laravelnet

networks:
    laravelnet:
        driver: bridge

volumes:
    dbdata:
        driver: local
